#ifndef WIDGETSLIB_GLOBAL_H
#define WIDGETSLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WIDGETSLIB_LIBRARY)
#  define WIDGETSLIB_EXPORT Q_DECL_EXPORT
#else
#  define WIDGETSLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // WIDGETSLIB_GLOBAL_H
